const records = [
  {key:'axis',name:'Axis',category:'survey',zone:'north',description:'A calibrated route through the northern ridgeline.',angle:'15deg',radius:'50%',rarity:'#fe5a00',accent:'#00ffa2'},
  {key:'relay',name:'Relay',category:'signal',zone:'east',description:'A signal post that maps changes along the eastern corridor.',angle:'45deg',radius:'10%',rarity:'#ffbb03',accent:'#fffa00'},
  {key:'strata',name:'Strata',category:'archive',zone:'west',description:'Layered observations from the western shelf.',angle:'72deg',radius:'50%',rarity:'#9452fa',accent:'#ff00f0'},
  {key:'vector',name:'Vector',category:'survey',zone:'east',description:'A directional study of travel and light.',angle:'-12deg',radius:'0%',rarity:'#fe5a00',accent:'#00ffa2'},
  {key:'beacon',name:'Beacon',category:'signal',zone:'north',description:'A high contrast marker in a sparse field.',angle:'32deg',radius:'50%',rarity:'#ffbb03',accent:'#fffa00'},
  {key:'index',name:'Index',category:'archive',zone:'east',description:'A compact collection of field measurements.',angle:'60deg',radius:'4%',rarity:'#9452fa',accent:'#ff00f0'},
  {key:'delta',name:'Delta',category:'survey',zone:'west',description:'Intersecting paths at the edge of the known map.',angle:'-36deg',radius:'50%',rarity:'#fe5a00',accent:'#00ffa2'},
  {key:'echo',name:'Echo',category:'signal',zone:'west',description:'Repeating traces in a quiet part of the network.',angle:'80deg',radius:'15%',rarity:'#ffbb03',accent:'#fffa00'}
];
function rootScale(){const w=innerWidth,h=innerHeight,portrait=h>=w;const rem=16*(portrait?(w/h>1080/1920?h/1920:w/1080):(w/h>2560/1440?h/1440:w/2560));document.documentElement.style.fontSize=`${rem}px`}
rootScale();addEventListener('resize',rootScale,{passive:true});
const grid=document.getElementById('recordsGrid');const category=document.getElementById('categoryFilter');const zone=document.getElementById('zoneFilter');const count=document.getElementById('recordCount');const dialog=document.getElementById('detailDialog');
function render(){const visible=records.filter(item=>(!category.value||item.category===category.value)&&(!zone.value||item.zone===zone.value));count.textContent=`${String(visible.length).padStart(2,'0')} / ${String(records.length).padStart(2,'0')}`;grid.replaceChildren(...visible.map((item,index)=>{const card=document.createElement('button');card.className='record-card';card.type='button';card.style.cssText=`--angle:${item.angle};--radius:${item.radius};--rarity:${item.rarity};--accent:${item.accent}`;card.innerHTML=`<div class="record-art" data-code="// ${item.key.toUpperCase()}"></div><div class="record-plate"><strong>${item.name}</strong><small>// ${item.key.toUpperCase()} &nbsp; ${String(index+1).padStart(2,'0')} / ${records.length}</small><span class="record-icons"><span>${item.category[0].toUpperCase()}</span><span>${item.zone[0].toUpperCase()}</span></span></div>`;card.setAttribute('aria-label',`Open ${item.name} field record`);card.addEventListener('click',()=>openDetail(item));return card}))}
function openDetail(item){document.getElementById('detailTitle').textContent=item.name;document.getElementById('detailIndex').textContent=`[ REC ] // ${String(records.indexOf(item)+1).padStart(2,'0')} / ${records.length}`;document.getElementById('detailMeta').innerHTML=`<span>CATEGORY / ${item.category.toUpperCase()}</span><span>ZONE / ${item.zone.toUpperCase()}</span>`;document.getElementById('detailDescription').textContent=item.description;document.getElementById('detailVisual').style.background=`linear-gradient(135deg,${item.accent},#fffa00)`;dialog.showModal()}
category.addEventListener('change',render);zone.addEventListener('change',render);document.getElementById('detailClose').addEventListener('click',()=>dialog.close());document.getElementById('detailBack').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});render();
const menu=document.getElementById('sideNav'),menuToggle=document.getElementById('menuToggle');menuToggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');menuToggle.setAttribute('aria-expanded',String(open));menuToggle.setAttribute('aria-label',open?'Close navigation':'Open navigation')});menu.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{menu.classList.remove('open');menuToggle.setAttribute('aria-expanded','false')}));
const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.18});document.querySelectorAll('.reveal').forEach(item=>revealObserver.observe(item));
const loader=document.getElementById('loader'),loaderBar=document.getElementById('loaderBar'),loaderPercent=document.getElementById('loaderPercent');const tasks=[document.fonts.ready,new Promise(resolve=>addEventListener('load',resolve,{once:true})),Promise.resolve(records.length)];let completed=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;Promise.allSettled(tasks.map(task=>Promise.resolve(task).finally(()=>{completed++;const progress=Math.round(completed/tasks.length*100);loaderBar.style.width=`${progress}%`;loaderPercent.textContent=`${progress}%`}))).then(()=>{loader.classList.add('leaving');document.body.classList.remove('loading');setTimeout(()=>loader.remove(),reduced?50:2500)});
