// Interactions measured live: what clicks, hovers, drags, keyboard, resize actually do, with the real code.
import { data, p, t, sub, a, observed, measured, inferred, rule, table, esc, excerpt, interactions as I, shotIf, readableLink } from './lib.mjs';
const J = v => esc(typeof v === 'string' ? v : JSON.stringify(v));
const tlRows = (tl, max = 12) => (tl || []).slice(0, max).map(e => [esc(e.element), `${e.first}–${e.last} ms`, String(e.n), esc(Object.entries(e.props || {}).map(([k, v]) => `${k}: ${v}`).join(' · ') + (e.classes && e.classes.length ? ' · classes ' + e.classes.map(c => `${c.t}ms +${c.added.join(',')}`).join('; ') : '') + (e.srcs && e.srcs.length ? ' · src ' + e.srcs.map(s => `${s.t}ms ${s.src}`).join('; ') : '')).slice(0, 260)]);
export const chapters = [
  { slug: 'interactions', title: 'Interactions measured live: clicks, hovers, drags, keyboard, resize, real-time calculations', html() {
    if (!I) return p('<strong>capture/interactions.json is missing — run tools/capture-interactions.mjs.</strong>');
    const out = [];
    out.push(t('Static images cannot prove behaviour, so every interactive mechanism below was driven in headless Chromium on the live site and its effect recorded (DOM, computed styles, store values, audio calls, mutation timelines), and the reconstructed code that produces that effect is quoted next to it. Where a calculation runs in real time (root font-size, operator-name fitting), the same algorithm was re-executed in the page and compared with what the site applied.'));
    // A. root font size
    if (I.rootFontSize) { out.push(sub('A. Root font-size recomputed at eight viewports'), measured('The html font-size was read after each viewport change and compared with the formula from applyRootFontSize. ' + (I.rootFontSize.every(r => r.match) ? 'All eight match to 0.01px.' : 'Mismatches: ' + I.rootFontSize.filter(r => !r.match).map(r => r.viewport).join(', ') + '.')), table(['Viewport', 'Orientation', 'Measured', 'Formula', 'Match'], I.rootFontSize.map(r => [r.viewport, r.orientation, r.measured, r.formula, r.match ? 'yes' : 'NO'])), excerpt(14577, 'function applyRootFontSize', 40)); }
    // B. rail
    if (I.railExpand) { out.push(sub('B. Navigation rail: hover expansion, section clicks, mute'), measured(`Hovering the rail: the :before panel transform went from ${J(I.railExpand.atRest.rail && 'none')} to ${J(I.railExpand.hovered.before)}, nav items widened to ${J(I.railExpand.hovered.navItemWidth && I.railExpand.hovered.navItemWidth.width)}, label opacity ${J(I.railExpand.atRest.label && I.railExpand.atRest.label.opacity)} → ${J(I.railExpand.hovered.label && I.railExpand.hovered.label.opacity)} with transform ${J(I.railExpand.hovered.label && I.railExpand.hovered.label.transform)}.`)); 
      if (I.navClicks) out.push(table(['Rail item', 'scrollY before → after', 'hash before → after', 'hash changed after', 'active index', 'overlay transform', 'sounds'], I.navClicks.map(n => [esc(n.key || String(n.index)), `${n.scrollBefore} → ${n.scrollAfter}`, `${n.hashBefore || '(none)'} → ${n.hashAfter}`, n.hashChangedAfterMs === null ? '—' : n.hashChangedAfterMs + ' ms', String(n.activeIndex), esc(n.overlayTransform), esc(n.sounds.join(', '))])));
      out.push(excerpt(83597, '"ontouchstart" in window || setHeaderExpanded(!0)', 8, { skip: -3 }), excerpt(83597, 'handleScrollThrottled = (0, lodashThrottle.A)', 26));
      if (I.mute) out.push(measured(`Mute button: localStorage ef-official-sound-control ${J(I.mute.storeBefore)} → ${J(I.mute.storeAfterClick)} → ${J(I.mute.storeAfterSecondClick)}; background audio ${J(I.mute.audioBefore)} → ${J(I.mute.audioAfterClick)} → ${J(I.mute.audioAfterSecondClick)}; media calls during the first click: ${J(I.mute.mediaCalls)}; button label "${esc(I.mute.buttonText || '')}".`)); }
    // C. operator stage
    if (I.avatarSwitch) { const ac = I.avatarClick || {}; out.push(sub('C. Character stage: avatar switch, 2D/3D switch, All Operators'), measured(`Avatar rail: ${I.avatarCount} switchItem elements are rendered (the component maps centerIndex−5 … centerIndex+6 and wraps the operator list); the active item was index ${ac.activeBefore}. A real mouse click at the centre of item ${ac.clickedIndex} (element under the pointer: ${J(ac.topAtPoint)}; method ${J(ac.clickMethod)}) made the active index ${ac.activeBefore} → ${ac.activeAfter}; readout "${esc(I.avatarSwitch.nameBefore || '')}" → "${esc(I.avatarSwitch.nameAfter || '')}", illustration ${esc(I.avatarSwitch.illustBefore || '')} → ${esc(I.avatarSwitch.illustAfter || '')}; sounds ${J(I.avatarSwitch.sounds.map(s => s.src))}. Item transforms after the click: ${J(ac.itemTransforms)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(I.avatarSwitch.timeline, 12)), shotIf('capture/interactions/stage-after-avatar-switch.png', 'stage after the avatar click'), excerpt(3492, 'getSwitchItemTransform = (railItemIndex, railCenterIndex, railIsPortrait) => {', 7), excerpt(3492, '(selectItem(itemIndex), SoundEffects.A.play(SoundEffects.d.char_click))', 6, { skip: -4 }), excerpt(3492, 'animeJsDefault.A.timeline()', 30, { skip: 0 }));
      if (I.switch3d) { const tg = I.switch3d.toggle || {}; const st = x => x ? `class "${esc(x.class.replace(/__[A-Za-z0-9_]{5}/g, ''))}", ::before content ${esc(x.before.content)} at ${esc(x.before.transform)}, background ${esc(x.background)}` : '(not found)';
        out.push(observed(`The 2D/3D switch is an empty div (${esc(I.switch3d.switcherMarkup || '')}): the knob is its ::before pseudo-element, whose content is "2D" or "3D" and whose translate3d moves it between the two ends of the pill. Clicking toggles the is3dMode state, which adds the active class; four browsers (vivo, OPPO, MIUI, Quark user agents) get noDisplay instead.`), measured(`Before the click: ${st(tg.before)}. After one click: ${st(tg.after)}. After a second click: ${st(tg.afterSecondClick)}. Sounds: ${J(tg.sounds)}. Transparent-video elements after the first click: ${J(tg.transparentVideo)}; media files requested: ${J(tg.videoRequests)}; console: ${J(tg.logs)}. This Chromium's canPlayType for H.264 is ${J(I.switch3d.canPlayH264 || '""')} (empty = cannot decode), so the clip could be assigned and requested but not decoded here; on a desktop browser with H.264 the same path renders the RGB+alpha clip through WebGL.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(tg.timeline, 10)), shotIf('capture/interactions/stage-3d-toggle.png', 'stage after clicking the 2D/3D switch'), excerpt(3492, '[isDowngraded, setIsDowngraded] = (0, React.useState)(!1);', 10), excerpt(3492, 'className: styles2().switchLayer,', 12), excerpt(3492, 'playEnterSequence = (0, React.useCallback)', 70)); }
      if (I.allOperators) out.push(measured(`"All Operators": opens a new tab = ${I.allOperators.opensNewTab}, URL ${esc(I.allOperators.url || '')}, sounds ${J(I.allOperators.sounds)}.`), excerpt(3492, 'window.open("".concat("/" + lang, "/operator"), "_blank")', 5, { skip: -4 })); }
    // D. lore
    if (I.lore) { const L = I.lore, ms = L.modelSwitch || {}, dg = L.drag || {}; out.push(sub('D. LORE point cloud: quality tier, model switch, drag'), measured(`Console on entering the section: ${J(L.renderLevelLog)}; canvas ${J(L.canvas)}. Dots at rest ${J(L.dots)} with codename "${esc(L.codenameBefore || '')}" and intro "${esc(L.introBefore || '')}…".`), measured(`Clicking the next arrow (${ms.clicked ? 'dispatched' : 'not found'}): codename "${esc(L.codenameBefore || '')}" → "${esc(ms.codenameAfter || '')}", dots ${J(ms.dotsAfter)}, intro "${esc(ms.introAfter || '')}…", canvas pixels changed = ${J(ms.canvasBytesChanged)}, sounds ${J(ms.sounds)}, console ${J(ms.logs)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(ms.timeline, 8)), excerpt(83597, 'SoundEffects.A.play(SoundEffects.d.model)', 12, { skip: -3 }), excerpt(83597, 'if (nextModelIndex === this.modelIndex || (0, swiper._)(this, switchingField)) return;', 14, { skip: -1 }), measured(`Drag: container cursor ${J(dg.cursor && dg.cursor.cursor)}; two idle frames 700 ms apart differ = ${J(dg.idleFramesDiffer)} (the scene auto-rotates and animates its particles, so the canvas is never static); after a ${dg.dragDistancePx}px horizontal mouse drag the canvas differs from the last idle frame = ${J(dg.canvasChangedAfterDrag)}. The rotation itself lives in the three.js scene (targetRotationY), not in any DOM transform, so the proof of what the drag does is the handler below rather than a style diff.`), excerpt(83597, '? (this.renderLevel = 2)', 12, { skip: -8 }), excerpt(83597, 'this.autoRotation && !this.isDragging && (this.targetRotationY += this.autoRotationSpeed)', 8, { skip: -2 }), excerpt(83597, '(this.handleMouseDown = (mouseDownEvent) => {', 26), shotIf('capture/interactions/lore-after-drag.png', 'LORE scene after the drag')); }
    // E. information
    if (I.information) { const i = I.information; out.push(sub('E. INFORMATION: thumbnail hover, next, play → media modal'), measured(`Thumbnails: ${i.thumbnails}; readout "${esc(i.readoutBefore || '')}" → "${esc(i.nextClick && i.nextClick.readoutAfter || '')}"; active index ${i.activeBefore} → ${i.nextClick && i.nextClick.activeAfter}; cover at rest ${J(i.coverRest)} → hovered ${J(i.coverHover)}; next-click sounds ${J(i.nextClick && i.nextClick.sounds)}; background video after next: ${J(i.nextClick && i.nextClick.bgVideo)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(i.nextClick && i.nextClick.timeline, 10)), measured(`Play: modal class ${J(i.play && i.play.modalClass)}, opacity/pointer-events ${J(i.play && i.play.modalOpacity)}, iframe ${J(i.play && i.play.iframe)}, audio while open ${J(i.play && i.play.audioState)}, media calls ${J(i.play && i.play.mediaCalls)}. Close: class ${J(i.close && i.close.modalClass)}, audio after close ${J(i.close && i.close.audioState)}, media calls ${J(i.close && i.close.mediaCalls)}.`), shotIf('capture/interactions/media-modal-open.png', 'media modal open over the information section'), excerpt(12914, '(0, React.useEffect)(() => {', 24)); }
    // F. calendar
    if (I.calendar) out.push(sub('F. CALENDAR pin states while scrolling'), measured(`Section height ${I.calendar.height}px. The stick container's position/class as the section scrolls:`), table(['Scroll from section top', 'stick classes', 'position', 'top', 'opacity', 'calendar opacity'], I.calendar.samples.map(s => [String(s.scrollFromSectionTop), esc(s.stick ? s.stick.classes : ''), esc(s.stick ? s.stick.position : ''), String(s.stick ? s.stick.top : ''), esc(s.stick ? s.stick.opacity : ''), esc(s.calendarOpacity || '')])), excerpt(83597, '[styles17().stickFixed]: "fixed" === stickMode', 6, { skip: -3 }));
    // G. gameplay
    if (I.gameplayNext) out.push(sub('G. GAMEPLAY album: next → clip-path reveal'), measured(`Index "${esc(I.gameplayNext.indexBefore || '')}" → "${esc(I.gameplayNext.indexAfter || '')}", sounds ${J(I.gameplayNext.sounds)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(I.gameplayNext.timeline, 14)), shotIf('capture/interactions/gameplay-after-next.png', 'album after clicking next'), excerpt(84245, 'clipRevealAnimation = (clipElement, direction, isReveal, clipDuration) =>', 30));
    // H. notice
    if (I.notice) { const n = I.notice; out.push(sub('H. NOTICE carousel: card states, next, detail button'), measured(`${n.cards} cards; active index ${n.activeIndexBefore} → ${n.nextClick && n.nextClick.activeIndexAfter}; Carousel_item transforms ${J(n.itemTransformsBefore)} → ${J(n.nextClick && n.nextClick.itemTransformsAfter)}; card states ${J(n.cardStates)}; readout ${J(n.nextClick && n.nextClick.readout)}; sounds ${J(n.nextClick && n.nextClick.sounds)}; detail button opens new tab ${J(n.detailButton && n.detailButton.opensNewTab)} to ${esc(n.detailButton && n.detailButton.url || '')} with sounds ${J(n.detailButton && n.detailButton.sounds)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(n.nextClick && n.nextClick.timeline, 10)), excerpt(83597, 'carouselItemTransform = (slotIndex, activeSlot) => {', 16)); }
    // I. footer language
    if (I.footerLanguage) out.push(sub('I. Footer language picker'), measured(`Options ${J(I.footerLanguage.options)}; dropdown ${J(I.footerLanguage.dropdownOpacity)}; choosing an option navigated to ${esc(I.footerLanguage.navigatedTo || '(no navigation recorded)')}.`), excerpt(46173, 'switchLanguage = (0, React.useCallback)', 8));
    // J. catalogue
    if (I.catalogue) { const c = I.catalogue; const nf = c.nameFit || []; out.push(sub('J. Catalogue: name-fit recomputed for every card, keyboard dropdown, filter, detail'), measured(`The bisection from OperatorCard was re-run in the page with the loaded SansBold face for ${nf.length} cards; ${nf.filter(x => x.match).length} applied font sizes match the recomputation within 0.002rem.`), table(['Name', 'Applied rem', 'Recomputed rem', 'Text width px', 'Box px', 'Match'], nf.map(x => [esc(x.name), String(x.appliedRem), String(x.recomputedRem), String(x.widthPx), String(x.boxPx), x.match ? 'yes' : 'NO'])), excerpt(50999, 'let fitName = () => {', 40), measured(`Dropdown keyboard: ${J(c.dropdownKeyboard)}. Filter "${esc(c.filter && c.filter.option || '')}": ${J(c.filter)}. Card click → detail: ${J(c.detail && { detailClass: c.detail.detailClass, stagePresent: c.detail.stagePresent, sounds: c.detail.sounds })}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(c.detail && c.detail.timeline, 10)), excerpt(50999, 'function FilterDropdown(props) {', 60), shotIf('capture/interactions/catalogue-detail.png', 'catalogue detail after clicking a card')); }
    // K. news
    if (I.news) { const n = I.news; out.push(sub('K. News: tab click, card hover, pagination, opener-aware close, portrait TextShrink'), measured(`Tabs ${J(n.tabs)}; after clicking the second tab: ${J(n.tabClick && { activeTab: n.tabClick.activeTab, textShift: n.tabClick.textShift, arrowOpacity: n.tabClick.arrowOpacity, cards: n.tabClick.cards, types: n.tabClick.types, sounds: n.tabClick.sounds })}. Card image hover scrim ${J(n.cardHover)}. Pagination ${J(n.pagination)}.`), table(['Element', 'Window', 'Mutations', 'What changed'], tlRows(n.tabClick && n.tabClick.timeline, 8)), measured(`Opening a card in a new tab (so window.opener exists): ${J(n.openedArticle)}.`), shotIf('capture/interactions/article-with-close.png', 'article opened from the index: the close icon is present'), measured(`Portrait (390×844): page size ${J(n.portrait && n.portrait.pageSize)}, pagination ${J(n.portrait && n.portrait.paginationType)}, titles ${J(n.portrait && n.portrait.titles)}.`), excerpt(92731, 'goToPage = (0, React.useCallback)', 28), excerpt(51967, 'shrinkText', 26), excerpt(67002, 'useCloseButton', 22)); }
    // L. mobile
    if (I.mobile) out.push(sub('L. Mobile header and menu (390×844, touch)'), measured(`Header ${J(I.mobile.header)}; menu transform ${J(I.mobile.menuBefore && I.mobile.menuBefore.transform)} → ${J(I.mobile.menuAfter && I.mobile.menuAfter.transform && I.mobile.menuAfter.transform.transform)} with classes ${J(I.mobile.menuAfter && I.mobile.menuAfter.classes)}; items ${J(I.mobile.menuAfter && I.mobile.menuAfter.items)}; tapping the second item: ${J(I.mobile.menuItemTap)}; operator drawer ${J(I.mobile.operatorDrawer)}.`), shotIf('capture/interactions/mobile-menu-open.png', 'mobile menu open'), shotIf('capture/interactions/mobile-operator.png', 'mobile operator drawer'), excerpt(83597, 'setHeaderExpanded(!isHeaderExpanded)', 6, { skip: -3 }));
    if (I.errors && Object.keys(I.errors).length) out.push(measured(`Scenarios that could not be completed in this container (recorded, not hidden): ${J(I.errors)}.`));
    out.push(inferred('Every interaction resolves to one of three kinds of change: a class toggle that the CSS animates (rail, tabs, menu, modal, calendar pin), an inline style written by anime.js or framer-motion (entrances, carousel, clip-path wipes), or a store/URL change (hash, mute flag, language path). There is no interaction that depends on a timer alone; everything is event-driven and ends in a settled state.'), rule('Implement interactions as class toggles animated by CSS where the end state is static, as JS timelines where the motion needs sequencing, and mirror navigation state into the URL hash and persisted stores.'));
    out.push(p('Raw data: ' + a('capture/interactions.json', '/capture/interactions.json') + '.'));
    return out.join('');
  } },
];
