// Chapter: the originals archive and the self-contained mirror hosted with the handbook.
import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { root, p, t, sub, a, observed, measured, inferred, rule, table, esc, code, SITE_URL } from './lib.mjs';
const J = f => existsSync(join(root, f)) ? JSON.parse(readFileSync(join(root, f), 'utf8')) : null;
const human = n => n > 1048576 ? (n / 1048576).toFixed(1) + ' MB' : n > 1024 ? (n / 1024).toFixed(0) + ' KB' : n + ' B';
export const chapters = [
  { slug: 'originals', title: 'Originals archive and self-contained mirror: the real assets, data and pages on this host', html() {
    const idx = J('archive/index.json'); if (!idx) return p('<strong>archive/index.json is missing — run tools/archive-originals.mjs then tools/build-mirror.mjs.</strong>');
    const files = idx.files.filter(f => f.file); const byType = {}; for (const f of files) { const k = (f.file.match(/\.([a-z0-9]+)$/) || [])[1] || '?'; byType[k] = byType[k] || { n: 0, b: 0 }; byType[k].n++; byType[k].b += f.bytes || 0; }
    const clipsArch = idx.clips.filter(c => c.archived); const clipsLeft = idx.clips.filter(c => !c.archived);
    const out = [];
    out.push(t('Everything the chapters describe can be opened in its original form on this host. The archive holds, verbatim and with SHA-256 digests, every file the depth-1 pages load, every answer the site\'s own API gave the pages, the server-components payload of every route, and the third-party SDK scripts; the mirror serves the original pages from that archive with their own markup, data and client navigation. Together they close the gaps that a document alone cannot: the backend answers, the media, the compiled source and the parts a headless capture could not render are all here as files, not descriptions.'));
    out.push(sub('A. What is archived'));
    out.push(observed(`Archived on ${idx.summary.archivedAt.slice(0, 10)}: ${idx.summary.files} files (${human(idx.summary.bytes)}), ${idx.summary.api} API responses, ${idx.summary.rsc} RSC payloads, ${idx.summary.clips.archived} of ${idx.summary.clips.total} operator clips. Each entry in ${a('archive/index.json', '/archive/index.json')} carries its original URL, size and SHA-256; the digests of the depth-1 files match the network manifest taken during the first capture unless the entry says the content changed.`));
    out.push(table(['Kind', 'Files', 'Bytes', 'Where'], Object.entries(byType).sort((x, y) => y[1].b - x[1].b).map(([k, v]) => [esc(k), String(v.n), human(v.b), a('archive/files/…', '/archive/files/')])));
    out.push(sub('B. The backend, as the pages saw it'));
    out.push(observed(`The pages talk to three services: the CMS at web-news.gryphline.com (/api/bulletin for lists and articles), the site origin (/api/content/info_video for the media list) and the SDK host web-api.gryphline.com (grayscale.json configuration). Every GET the client built while the news index was driven through all its tabs and pages, every article those lists name (${idx.api.filter(x => /\/api\/bulletin\/\d+/.test(x.url)).length} articles) and every page of the video list were recorded with the exact URL the client requests, so a child site can answer them from static files or copy their shapes.`));
    out.push(table(['Request (as the client builds it)', 'Status', 'Bytes', 'Archived answer'], idx.api.slice(0, 24).map(x => [esc(x.url.replace(/^https?:\/\//, '')), String(x.status), String(x.bytes), a(x.file.replace('archive/api/', ''), '/' + x.file)]).concat(idx.api.length > 24 ? [[`… ${idx.api.length - 24} more in archive/api/index.json`, '', '', a('index', '/archive/api/index.json')]] : [])));
    out.push(observed(`Client navigation: Next.js fetches a React Server Components payload for the target route (header rsc: 1). The payload of every route is archived under ${a('archive/rsc/', '/archive/rsc/')} (${idx.rsc.map(r => esc(r.route) + ' ' + human(r.bytes)).join(', ')}), so the mirror's router navigates without the origin server.`));
    out.push(inferred('What cannot be archived: the per-session answers of the SDK\'s own services (regular/check, cookie_store/account_token, event logging). The mirror lets those calls go to their live hosts, where the browser blocks them for a foreign origin exactly as it did for the local mirror; a child site replaces them with its own consent, login and analytics.'));
    out.push(sub('C. The media'));
    out.push(observed(`All ${files.filter(f => /\.(png|jpg|jpeg|webp|svg|mp4|mp3|json)$/.test(f.file)).length} images, videos, sounds and Lottie files the depth-1 pages load are archived, plus the images referenced by ${idx.api.filter(x => /\/api\/bulletin\/\d+/.test(x.url)).length} archived articles up to the size budget. The character stage's transparent-video clips are ${human(idx.summary.clips.totalBytes)} for ${idx.summary.clips.total} clips; GitHub Pages serves at most 1 GB per site, so ${clipsArch.length} clips are archived (${clipsArch.map(c => esc(c.operator + '/' + c.kind)).join(', ')}) and the other ${clipsLeft.length} are listed with URL, size and operator in ${a('archive/clips-index.json', '/archive/clips-index.json')}; the mirror loads them from the live CDN when the stage needs them, and tools/archive-originals.mjs --clips=all fetches every one for a local copy.`));
    out.push(sub('D. The source, three ways'));
    out.push(observed(`The compiled chunks exactly as shipped (${files.filter(f => /_next\/static\/chunks\//.test(f.file)).length} files under ${a('archive/files/web-static.hg-cdn.com/…/_next/static/chunks/', '/archive/files/web-static.hg-cdn.com/endfield/official-v4/_next/static/chunks/')}), the same chunks beautified (${a('source/beautified/', '/source/beautified/')}), split into 708 named modules (${a('source/modules/', '/source/modules/')}, ${a('source/MODULE-MAP.md', '/source/MODULE-MAP.md')}) and the first-party modules renamed for reading (${a('source/readable/', '/source/readable/')}). The original TypeScript and JSX were never published; what a child site builds from is the readable layer, checked against the shipped chunk when a detail matters.`));
    out.push(sub('E. The mirror'));
    const mi = J('mirror/index.json') || { copies: {}, api: {}, rsc: {} }; const copyList = Object.keys(mi.copies); const apiCopies = Object.values(mi.api).filter(v => v.startsWith('/mirror/')).length; const rscCopies = Object.values(mi.rsc).filter(v => v.startsWith('/mirror/')).length;
    out.push(observed(`The mirror is the archived server response of each route, served as a static file, with its URLs rewritten and one adapter script added in the document head. The rewrite points every static asset tag and every URL inside the embedded flight data at the archived file (the flight data is rewritten row by row, so the byte-length prefix of each text row is recomputed and the client parser reads it as before); the markup, data and order of the page are otherwise the original response. The adapter answers the page\'s API and RSC requests from the archive, redirects script, image, video and font loads to archived copies when they exist, and lets anything not archived reach its original URL. Routes: ${['/en-us', '/en-us/operator', '/en-us/news', '/en-us/protocol/privacy_policy', '/en-us/protocol/terms_of_service'].map(r => a(r, r)).join(', ')}, plus ${idx.api.filter(x => /\/api\/bulletin\/\d+/.test(x.url)).length - 1} archived articles at /en-us/news/<id>: each is the article shell with that article\'s archived record in its flight data and in its server-rendered body (the article at /en-us/news/7013 is this handbook).`));
    out.push(observed(`Three kinds of archived file name CDN URLs inside themselves and are served from rewritten copies under ${a('mirror/', '/mirror/index.json')} while the originals stay untouched in the archive: ${copyList.length} scripts and stylesheets under mirror/files/ (the webpack runtime\'s public path pointed at the archive tree, the SDK bundles\' asset expressions resolved to the archived fonts and images, url() in the stylesheets: ${copyList.map(c => esc(c.replace(/^.*\//, ''))).slice(0, 6).join(', ')}${copyList.length > 6 ? ', …' : ''}), ${apiCopies} API answers under mirror/api/ (the cover and article images they name), and ${rscCopies} RSC payloads under mirror/rsc/. mirror/index.json lists every copy against its archive file.`));
    const vm = J('verification/mirror-report.json'); if (vm) out.push(measured(`tools/verify-mirror.mjs loaded the mirror from a plain static server: ${vm.results.filter(r => r.ok).length} of ${vm.results.length} checks passed — ${vm.results.map(r => (r.ok ? '✓ ' : '✗ ') + r.name).join('; ')}.`));
    out.push(code(`// mirror adapter (head only), excerpt — tools/build-mirror.mjs
const archived = u => { const x = new URL(u, location.href); if (!hostOf[x.host]) return null;
  const p = '/archive/files/' + x.host + decodeURIComponent(x.pathname); return FILES.has(p) ? (LOCAL[p] || p) : null; };
const unarchived = u => { /* a local archive path with no file behind it → the original https:// URL */ };
XMLHttpRequest.prototype.open = function (m, u, ...r) { const k = key(u);
  if (m === 'GET' && API[k]) u = location.origin + API[k]; else { const a = archived(u); if (a) u = a; }
  return open.call(this, m, u, ...r); };
window.fetch = async function (input, init) { /* rsc: 1 → RSC[route], API[key] → the archived answer, assets → archived(u) */ };
// flight rows: \`id:T<hex byte length>,text\` — a URL rewritten inside the text changes the length, so every row is re-emitted
const rewriteFlight = text => { /* parse rows, rewriteUrls(row), recompute T lengths, concat */ };`, { max: 20 }));
    out.push(sub('F. What this changes for a child site'));
    out.push(rule('Build the backend to answer the archived requests in the archived shapes (archive/api/index.json is the contract; mirror/api/ shows the same answers with the media on this host), serve media from your own CDN with the same paths, keep the SDK calls behind your own consent and login, and use the mirror as the reference rendering: open a mirrored page and a child page side by side at 1440×900 and compare.'));
    out.push(inferred('With the archive and the mirror on the same host as this handbook, the only things a reader cannot take from here are Gryphline\'s live services and the rights to the material: everything that can be a file is a file.'));
    return out.join('');
  } },
];
